imports:
    - { resource: services.forms.yml }
    - { resource: services.managers.yml }
    - { resource: services.voter.yml }

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    jsn.security.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [@doctrine]