// Generated by CoffeeScript 1.10.0
define(['jquery'], function(jquery) {
  $('#jobapplication_uploadfile').click(function() {
    $('#jobapplication_uploadedFile').trigger('click');
  });
  $('#jobapplication_uploadedFile').change(function() {
    var filename;
    filename = $('#jobapplication_uploadedFile').val().split('\\').pop();
    filename = 'Uploaded File (' + $('#jobapplication_uploadedFile').val().split('\\').pop() + ')';
    $('#new-resume label label').text(filename);
    $('#new-resume').show();
    $('#jobapplication_resumeselect_0').prop("checked", true);
  });
});
