// Generated by CoffeeScript 1.10.0
define(['selectize'], function(selectize) {
  $("#form_skills").selectize({
    plugins: ['remove_button'],
    valueField: 'skill',
    labelField: 'skill',
    searchField: 'skill',
    create: true,
    load: function(query, callback) {
      if (!query.length) {
        return callback();
      }
      $.ajax({
        url: '/api/worker/skills/' + encodeURIComponent(query),
        type: 'GET',
        error: function() {
          return callback();
        },
        success: function(res) {
          return callback(res.slice(0, 10));
        }
      });
    }
  });
});
