<?php

namespace AppBundle\Entity;

/**
 * JobApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
