<?php

namespace AppBundle\Entity;

/**
 * RateTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
