<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{
    public function searchSkills($searchKey)
    {
        $skills = $this->createQueryBuilder('s')
            ->where('s.skill LIKE :searchKey')
            ->setParameter('searchKey', '%' . $searchKey . '%')
            ->getQuery()
            ->getResult();
        return $skills;
    }
}
