<?php

namespace AppBundle\Entity;

/**
 * UserResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
