<?php

namespace AppBundle\Entity;

/**
 * UserServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
